---
grails:
    profile: rest-api
    codegen:
        defaultPackage: com.ligarisma.booking
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
  jdbc:
    time_zone: 'UTC'
  singleSession: true
  flush:
    mode: manual
  connection:
    useUnicode: true
    charSet: utf8
    characterEncoding: utf8
    provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
  hikari:
    minimumIdle: '5'
    maximumPoolSize: '20'
    idleTimeout: '30000'
    dataSourceClassName: org.mariadb.jdbc.MySQLDataSource
  cache:
    queries: false
    use_query_cache: false
    use_second_level_cache: false

dataSource:
      pooled: false
      jmxExport: true
      jmxEnabled: true
      driverClassName: org.mariadb.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

environments:
    development:
      grails.plugin.springsecurity:
          active: true          # change this to false to temporarily disable springsecurity
          debug.useFilter: true # show debug message for security chain filter
      dataSource.dbCreate: update
          # primary data source
      hibernate.hikari.dataSource:
        url: "jdbc:mysql://192.168.56.102/book_room"
        user: root
        password: 'root'
    test:
      dataSource:
             dbCreate: update
             url : "jdbc:mysql://192.168.56.102/book_room"
    production:
       dataSource:
              dbCreate: update
              url : "jdbc:mysql://192.168.56.102/book_room"
              properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
